Updates dependency management
RockefellerArchiveCenter/argo pull request #160
Opened 2021-06-30 21:05 UTC by helrond

- Adds dependabot config
- Updates pre-commit config
- Separates and updates dependencies

Updating to Django 3 requires the `DEFAULT_AUTO_FIELD` setting.
Updating asterism requires an additional migration.

2021-07-01 21:01 UTC, HaSistrunk approved these changes

2021-07-06 16:53 UTC, bonniegee requested changes

2021-07-06 16:53 UTC, bonniegee commented on .pre-commit-config.yaml
> +  rev: 6.0.1
This should likely be updated to 6.2

2021-07-07 12:30 UTC, bonniegee commented
Based on how the build is failing, I think you may need to update your local pip-compile version and/or re-run pip-compile locally (also applies to RockefellerArchiveCenter/pisces#447).

2021-07-07 14:37 UTC, bonniegee approved these changes

2021-07-09 19:02 UTC, p-galligan approved these changes

2021-07-12 13:29 UTC, merged