Update workflows
RockefellerArchiveCenter/argo pull request #310
Opened 2024-09-09 19:36 UTC by p-galligan

Migrates from Travis to GHA

2024-09-09 23:25 UTC, helrond requested changes
Just one small thing - I think we need to pull in submodules for deploy as well because that code needs to be available to the app.

Branch rules also need to be updated.

2024-09-09 23:25 UTC, helrond commented on .github/workflows/deploy.yml
> +        uses: actions/checkout@v4
I think it might be necessary to add submodules here too.

2024-09-10 13:22 UTC, helrond commented
@p-galligan Branch protection rules need to be updated.

2024-09-10 15:09 UTC, p-galligan commented
> @p-galligan Branch protection rules need to be updated.

Thanks! Got them.

2024-09-10 15:10 UTC, HaSistrunk approved these changes

2024-09-10 15:37 UTC, helrond approved these changes

2024-09-10 15:45 UTC, merged